--------------------------------------------------------
--  File created - Sunday-July-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER, 
	"CUSTOMER_NAME" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"JOIN_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER, 
	"EMP_NAME" VARCHAR2(100 BYTE), 
	"JOB_TITLE" VARCHAR2(50 BYTE), 
	"SALARY" NUMBER(10,2), 
	"HIRE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE_AUDIT
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."EMPLOYEE_AUDIT" 
   (	"AUDIT_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"ACTION_DATE" DATE, 
	"ACTION_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."INVENTORY" 
   (	"INVENTORY_ID" NUMBER, 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER DEFAULT 0, 
	"SUPPLIER_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_DATE" DATE DEFAULT SYSDATE, 
	"CUSTOMER_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."ORDER_DETAILS" 
   (	"DETAIL_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."PAYMENT" 
   (	"PAYMENT_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"PAYMENT_DATE" DATE DEFAULT SYSDATE, 
	"AMOUNT" NUMBER(10,2), 
	"PAYMENT_METHOD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER(10,2), 
	"CATEGORY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "COFFEE30837"."SUPPLIER" 
   (	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(100 BYTE), 
	"CONTACT_PERSON" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View SALES_REPORT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "COFFEE30837"."SALES_REPORT" ("ORDER_ID", "ORDER_DATE", "CUSTOMER_NAME", "PRODUCT_NAME", "QUANTITY", "TOTAL_PRICE", "PAYMENT_METHOD") AS 
  SELECT 
    O.Order_ID,
    O.Order_Date,
    C.Customer_Name,
    P.Product_Name,
    OD.Quantity,
    (OD.Quantity * P.Price) AS Total_Price,
    PAY.Payment_Method
FROM ORDERS O
JOIN CUSTOMER C ON O.Customer_ID = C.Customer_ID
JOIN ORDER_DETAILS OD ON O.Order_ID = OD.Order_ID
JOIN PRODUCT P ON OD.Product_ID = P.Product_ID
JOIN PAYMENT PAY ON O.Order_ID = PAY.Order_ID
;
REM INSERTING into COFFEE30837.CATEGORY
SET DEFINE OFF;
Insert into COFFEE30837.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION) values (1,'Coffee','Hot and Cold Coffee');
REM INSERTING into COFFEE30837.CUSTOMER
SET DEFINE OFF;
Insert into COFFEE30837.CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,JOIN_DATE) values (1,'Mohamed Mahel','0781234567','mohamed@email.com','Kigali',to_date('04-JUL-26','DD-MON-RR'));
REM INSERTING into COFFEE30837.EMPLOYEE
SET DEFINE OFF;
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (31,'Mohamed Mahel','Manager',5000,to_date('05-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (2,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (3,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (4,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (5,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (6,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (7,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (8,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (9,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (10,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (11,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (12,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (13,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (14,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (15,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (16,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (17,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (18,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (19,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (20,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (21,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (22,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (23,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (24,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (25,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (26,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (27,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (28,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (29,'Mohamed Mahel','Manager',5000,to_date('04-JUL-26','DD-MON-RR'));
Insert into COFFEE30837.EMPLOYEE (EMPLOYEE_ID,EMP_NAME,JOB_TITLE,SALARY,HIRE_DATE) values (30,'Mohamed Mahel','Manager',5000,to_date('05-JUL-26','DD-MON-RR'));
REM INSERTING into COFFEE30837.EMPLOYEE_AUDIT
SET DEFINE OFF;
Insert into COFFEE30837.EMPLOYEE_AUDIT (AUDIT_ID,EMP_ID,ACTION_DATE,ACTION_TYPE) values (1,1,to_date('04-JUL-26','DD-MON-RR'),'DELETE');
REM INSERTING into COFFEE30837.INVENTORY
SET DEFINE OFF;
REM INSERTING into COFFEE30837.ORDERS
SET DEFINE OFF;
REM INSERTING into COFFEE30837.ORDER_DETAILS
SET DEFINE OFF;
REM INSERTING into COFFEE30837.PAYMENT
SET DEFINE OFF;
REM INSERTING into COFFEE30837.PRODUCT
SET DEFINE OFF;
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (1,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (2,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (3,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (4,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (5,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (6,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (7,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (8,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (9,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (10,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (11,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (12,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (13,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (14,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (15,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (16,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (17,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (18,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (19,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (20,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (21,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (22,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (23,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (24,'Espresso',2500,1);
Insert into COFFEE30837.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,CATEGORY_ID) values (25,'Espresso',2500,1);
REM INSERTING into COFFEE30837.SUPPLIER
SET DEFINE OFF;
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (1,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (2,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (3,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (4,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (5,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (6,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (7,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (8,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (9,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (10,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (11,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (12,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (13,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (14,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (15,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (16,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (17,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (18,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (19,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (20,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (21,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (22,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (23,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (24,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (25,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (26,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (27,'Coffee Beans Supplier','John Doe','0780000000');
Insert into COFFEE30837.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_PERSON,PHONE) values (28,'Coffee Beans Supplier','John Doe','0780000000');
REM INSERTING into COFFEE30837.SALES_REPORT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008221
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008221" ON "COFFEE30837"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008222
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008222" ON "COFFEE30837"."CUSTOMER" ("PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008223
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008223" ON "COFFEE30837"."CUSTOMER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008225
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008225" ON "COFFEE30837"."CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008226
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008226" ON "COFFEE30837"."CATEGORY" ("CATEGORY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008228
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008228" ON "COFFEE30837"."EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008230
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008230" ON "COFFEE30837"."SUPPLIER" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008233
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008233" ON "COFFEE30837"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008236
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008236" ON "COFFEE30837"."INVENTORY" ("INVENTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008238
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008238" ON "COFFEE30837"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008242
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008242" ON "COFFEE30837"."ORDER_DETAILS" ("DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008246
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008246" ON "COFFEE30837"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008248
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008248" ON "COFFEE30837"."EMPLOYEE_AUDIT" ("AUDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008225
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008225" ON "COFFEE30837"."CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008226
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008226" ON "COFFEE30837"."CATEGORY" ("CATEGORY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008221
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008221" ON "COFFEE30837"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008222
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008222" ON "COFFEE30837"."CUSTOMER" ("PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008223
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008223" ON "COFFEE30837"."CUSTOMER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008228
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008228" ON "COFFEE30837"."EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008248
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008248" ON "COFFEE30837"."EMPLOYEE_AUDIT" ("AUDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008236
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008236" ON "COFFEE30837"."INVENTORY" ("INVENTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008238
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008238" ON "COFFEE30837"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008242
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008242" ON "COFFEE30837"."ORDER_DETAILS" ("DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008246
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008246" ON "COFFEE30837"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008233
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008233" ON "COFFEE30837"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008230
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFEE30837"."SYS_C008230" ON "COFFEE30837"."SUPPLIER" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_AUDIT_EMPLOYEE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COFFEE30837"."TRG_AUDIT_EMPLOYEE" 
AFTER DELETE ON EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE_AUDIT (Audit_ID, Emp_ID, Action_Date, Action_Type)
    VALUES ((SELECT NVL(MAX(Audit_ID), 0) + 1 FROM EMPLOYEE_AUDIT), :OLD.Employee_ID, SYSDATE, 'DELETE');
END;

/
ALTER TRIGGER "COFFEE30837"."TRG_AUDIT_EMPLOYEE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BLOCK_OFF_HOURS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COFFEE30837"."TRG_BLOCK_OFF_HOURS" 
BEFORE INSERT OR UPDATE OR DELETE ON ORDERS
BEGIN

    IF (TO_CHAR(SYSDATE, 'HH24') < 8 OR TO_CHAR(SYSDATE, 'HH24') >= 17) THEN
        RAISE_APPLICATION_ERROR(-20001, 'System access is restricted during non-working hours.');
    END IF;
END;

/
ALTER TRIGGER "COFFEE30837"."TRG_BLOCK_OFF_HOURS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_AUDIT_EMPLOYEE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COFFEE30837"."TRG_AUDIT_EMPLOYEE" 
AFTER DELETE ON EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE_AUDIT (Audit_ID, Emp_ID, Action_Date, Action_Type)
    VALUES ((SELECT NVL(MAX(Audit_ID), 0) + 1 FROM EMPLOYEE_AUDIT), :OLD.Employee_ID, SYSDATE, 'DELETE');
END;

/
ALTER TRIGGER "COFFEE30837"."TRG_AUDIT_EMPLOYEE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BLOCK_OFF_HOURS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "COFFEE30837"."TRG_BLOCK_OFF_HOURS" 
BEFORE INSERT OR UPDATE OR DELETE ON ORDERS
BEGIN

    IF (TO_CHAR(SYSDATE, 'HH24') < 8 OR TO_CHAR(SYSDATE, 'HH24') >= 17) THEN
        RAISE_APPLICATION_ERROR(-20001, 'System access is restricted during non-working hours.');
    END IF;
END;

/
ALTER TRIGGER "COFFEE30837"."TRG_BLOCK_OFF_HOURS" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADD_CATEGORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEE30837"."ADD_CATEGORY" (
    p_name IN VARCHAR2,
    p_desc IN VARCHAR2
) AS
BEGIN
    INSERT INTO CATEGORY (Category_ID, Category_Name, Description)
    VALUES ( (SELECT NVL(MAX(Category_ID), 0) + 1 FROM CATEGORY), p_name, p_desc);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Category added successfully!');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_EMPLOYEE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEE30837"."ADD_EMPLOYEE" (
    p_name IN VARCHAR2,
    p_job IN VARCHAR2,
    p_salary IN NUMBER
) AS
BEGIN
    INSERT INTO EMPLOYEE (Employee_ID, Emp_Name, Job_Title, Salary, Hire_Date)
    VALUES ( (SELECT NVL(MAX(Employee_ID), 0) + 1 FROM EMPLOYEE), p_name, p_job, p_salary, SYSDATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Employee added successfully!');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_ORDER_WITH_PAYMENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEE30837"."ADD_ORDER_WITH_PAYMENT" (
    p_cust_id IN NUMBER,
    p_emp_id IN NUMBER,
    p_amount IN NUMBER,
    p_method IN VARCHAR2
) AS
    v_order_id NUMBER;
BEGIN

    SELECT NVL(MAX(Order_ID), 0) + 1 INTO v_order_id FROM ORDERS;


    INSERT INTO ORDERS (Order_ID, Order_Date, Customer_ID, Employee_ID)
    VALUES (v_order_id, SYSDATE, p_cust_id, p_emp_id);


    INSERT INTO PAYMENT (Payment_ID, Order_ID, Payment_Date, Amount, Payment_Method)
    VALUES ((SELECT NVL(MAX(Payment_ID), 0) + 1 FROM PAYMENT), v_order_id, SYSDATE, p_amount, p_method);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Order ' || v_order_id || ' and Payment added successfully!');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_PRODUCT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEE30837"."ADD_PRODUCT" (
    p_name IN VARCHAR2,
    p_price IN NUMBER,
    p_cat_id IN NUMBER
) AS
BEGIN
    INSERT INTO PRODUCT (Product_ID, Product_Name, Price, Category_ID)
    VALUES ( (SELECT NVL(MAX(Product_ID), 0) + 1 FROM PRODUCT), p_name, p_price, p_cat_id);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Product added successfully!');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_SUPPLIER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "COFFEE30837"."ADD_SUPPLIER" (
    p_name IN VARCHAR2,
    p_contact IN VARCHAR2,
    p_phone IN VARCHAR2
) AS
BEGIN
    INSERT INTO SUPPLIER (Supplier_ID, Supplier_Name, Contact_Person, Phone)
    VALUES ( (SELECT NVL(MAX(Supplier_ID), 0) + 1 FROM SUPPLIER), p_name, p_contact, p_phone);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Supplier added successfully!');
END;

/
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "COFFEE30837"."CATEGORY" ADD UNIQUE ("CATEGORY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."CUSTOMER" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."CUSTOMER" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "COFFEE30837"."CUSTOMER" ADD UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "COFFEE30837"."CUSTOMER" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."EMPLOYEE" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."EMPLOYEE" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_AUDIT
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."EMPLOYEE_AUDIT" ADD PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."INVENTORY" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."INVENTORY" ADD PRIMARY KEY ("INVENTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."ORDER_DETAILS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."ORDER_DETAILS" ADD PRIMARY KEY ("DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."PAYMENT" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."PAYMENT" ADD PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."PRODUCT" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."SUPPLIER" MODIFY ("SUPPLIER_NAME" NOT NULL ENABLE);
  ALTER TABLE "COFFEE30837"."SUPPLIER" ADD PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."INVENTORY" ADD CONSTRAINT "FK_SUPPLIER" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "COFFEE30837"."SUPPLIER" ("SUPPLIER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."ORDERS" ADD CONSTRAINT "FK_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "COFFEE30837"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "COFFEE30837"."ORDERS" ADD CONSTRAINT "FK_EMPLOYEE" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "COFFEE30837"."EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."ORDER_DETAILS" ADD CONSTRAINT "FK_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "COFFEE30837"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "COFFEE30837"."ORDER_DETAILS" ADD CONSTRAINT "FK_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "COFFEE30837"."PRODUCT" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."PAYMENT" ADD CONSTRAINT "FK_ORDER_PAYMENT" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "COFFEE30837"."ORDERS" ("ORDER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "COFFEE30837"."PRODUCT" ADD CONSTRAINT "FK_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "COFFEE30837"."CATEGORY" ("CATEGORY_ID") ENABLE;
      
      SELECT CUSTOMER_NAME, COUNT(*)
FROM COFFEE30837.CUSTOMER
GROUP BY CUSTOMER_NAME
HAVING COUNT(*) > 1;
DELETE FROM COFFEE30837.CUSTOMER
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM COFFEE30837.CUSTOMER
    GROUP BY CUSTOMER_NAME
);

DELETE FROM COFFEE30837.CUSTOMER
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM COFFEE30837.CUSTOMER
    GROUP BY CUSTOMER_NAME
);

DELETE FROM COFFEE30837.CUSTOMER
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM COFFEE30837.CUSTOMER
    GROUP BY CUSTOMER_NAME
);


DELETE FROM COFFEE30837.CUSTOMER
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM COFFEE30837.CUSTOMER
    GROUP BY CUSTOMER_NAME
);
COMMIT;

ALTER TABLE COFFEE30837.CUSTOMER ADD CONSTRAINT UNIQUE_CUST_NAME UNIQUE (CUSTOMER_NAME);

INSERT INTO COFFEE30837.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, PHONE) VALUES (4, 'Jean', '0781111111');
INSERT INTO COFFEE30837.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, PHONE) VALUES (5, 'Alice', '0782222222');
INSERT INTO COFFEE30837.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, PHONE) VALUES (6, 'Marie', '0783333333');
INSERT INTO COFFEE30837.CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, PHONE) VALUES (7, 'Eric', '0784444444');
COMMIT;


DELETE FROM COFFEE30837.PRODUCT
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM COFFEE30837.PRODUCT
    GROUP BY PRODUCT_NAME
);


DELETE FROM COFFEE30837.SUPPLIER
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM COFFEE30837.SUPPLIER
    GROUP BY SUPPLIER_NAME
);

COMMIT;
INSERT INTO COFFEE30837.PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE, CATEGORY_ID) VALUES (2, 'Cappuccino', 3000, 1);
INSERT INTO COFFEE30837.PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE, CATEGORY_ID) VALUES (3, 'Latte', 3500, 1);
INSERT INTO COFFEE30837.PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE, CATEGORY_ID) VALUES (4, 'Americano', 2000, 1);
INSERT INTO COFFEE30837.PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE, CATEGORY_ID) VALUES (5, 'Mocha', 4000, 1);

INSERT INTO COFFEE30837.EMPLOYEE (EMPLOYEE_ID, EMP_NAME, JOB_TITLE, SALARY, HIRE_DATE) VALUES (31, 'Alice Mugabo', 'Manager', 6000, TO_DATE('01-JUL-26', 'DD-MON-RR'));
INSERT INTO COFFEE30837.EMPLOYEE (EMPLOYEE_ID, EMP_NAME, JOB_TITLE, SALARY, HIRE_DATE) VALUES (32, 'Jean Claude', 'Barista', 4500, TO_DATE('02-JUL-26', 'DD-MON-RR'));
INSERT INTO COFFEE30837.EMPLOYEE (EMPLOYEE_ID, EMP_NAME, JOB_TITLE, SALARY, HIRE_DATE) VALUES (33, 'Marie Uwase', 'Cashier', 4000, TO_DATE('03-JUL-26', 'DD-MON-RR'));

INSERT INTO COFFEE30837.SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_PERSON, PHONE) VALUES (2, 'Rwanda Coffee Co', 'Eric Habimana', '0789999999');
INSERT INTO COFFEE30837.SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_PERSON, PHONE) VALUES (3, 'Green Hills Beans', 'Sarah Keza', '0788888888');

DELETE FROM COFFEE30837.EMPLOYEE 
WHERE EMP_NAME = 'Mohamed Mahel';
COMMIT;


INSERT INTO COFFEE30837.EMPLOYEE (EMPLOYEE_ID, EMP_NAME, JOB_TITLE, SALARY, HIRE_DATE) 
VALUES (31, 'Alice Mugabo', 'Manager', 6000, TO_DATE('01-JUL-26', 'DD-MON-RR'));

INSERT INTO COFFEE30837.EMPLOYEE (EMPLOYEE_ID, EMP_NAME, JOB_TITLE, SALARY, HIRE_DATE) 
VALUES (32, 'Jean Claude', 'Barista', 4500, TO_DATE('02-JUL-26', 'DD-MON-RR'));

INSERT INTO COFFEE30837.EMPLOYEE (EMPLOYEE_ID, EMP_NAME, JOB_TITLE, SALARY, HIRE_DATE) 
VALUES (33, 'Marie Uwase', 'Cashier', 4000, TO_DATE('03-JUL-26', 'DD-MON-RR'));

INSERT INTO COFFEE30837.EMPLOYEE (EMPLOYEE_ID, EMP_NAME, JOB_TITLE, SALARY, HIRE_DATE) 
VALUES (34, 'Eric Habimana', 'Barista', 4200, TO_DATE('04-JUL-26', 'DD-MON-RR'));

COMMIT;



 